---
dependencies: []

galaxy_info:
  role_name: acmedns
  author: snoord
  description: ACME DNS challenges with Cloudflare or Route53
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - xenial
        - yakkety
        - zesty
        - artful
        - bionic
        - cosmic
        - disco
        - eoan
        - focal
  galaxy_tags:
    - acme
    - letsencrypt
    - dns
    - networking
